descriptions = [
    "Bacterial spot is caused by the bacterium Xanthomonas campestris pv. vesicatoria, which overwinters on crop debris and spreads in warm, wet conditions. Infected leaves develop small, water-soaked spots that quickly turn dark brown and may coalesce, leading to large necrotic patches surrounded by yellow halos. As the disease progresses, leaves yellow and drop prematurely, reducing plant vigor and yield. Control measures include using certified disease-free seed or transplants, applying copper-based foliar sprays at first symptom appearance, and practicing crop rotation with non-solanaceous crops for at least two years.",
    "Early blight, caused by the fungus Alternaria solani, often emerges in warm, humid conditions and spreads via wind-borne spores and splashing rain. It presents as concentric rings (“target spots”) on older leaves, which then yellow and drop, leading to defoliation and reduced fruit set. Cultural controls include removing and destroying infected leaves, staking plants to improve air circulation, and applying fungicides such as chlorothalonil or strobilurins at regular intervals. Maintaining even soil moisture and mulching to prevent soil splash also helps limit spore dispersal.",
    "Healthy leaves show uniform green color without lesions or discoloration. They are firm, turgid, and free of abnormal spots, mold, or distortion. Consistent watering, balanced fertilization, and proper exposure to sunlight and air circulation help maintain leaf health. Regular monitoring and preventive treatments (e.g., foliar nutrients) support continued vigor.",
    "Late blight, caused by the oomycete Phytophthora infestans, thrives in cool, wet weather and is infamous for rapid, devastating outbreaks. Leaf lesions appear as large, irregularly shaped dark patches, often with a pale green border; under humid conditions a white fuzzy sporulation may be visible on the undersides. Destroying volunteer plants, avoiding overhead irrigation, and applying protective fungicides (e.g. copper or fosetyl-Al) at the first sign of disease are key controls. Promptly remove and burn infected plant material to prevent sporangia from spreading to healthy foliage.",
    "Leaf mold of tomato is caused by the fungus Passalora fulva (formerly Cladosporium fulvum) and favors high humidity with limited air movement. Symptoms include pale yellow to olive-green patches on the upper leaf surface and a dense olive-green velvety growth on the underside. Improving ventilation in greenhouses or spacing plants in the field reduces humidity and slows disease development. Fungicide treatments with chlorothalonil or copper formulations can be effective when applied at early stages, and resistant cultivars are available.",
    "Tomato mosaic virus (ToMV) and related tobamoviruses infect leaves systemically, causing mottled light and dark green “mosaic” patterns, leaf distortion, and stunted growth. The virus is mechanically transmitted—on hands, tools, or via seed—so strict hygiene and use of virus-free seed are essential. Infected plants cannot be cured; control relies on rogueing (removing) symptomatic plants immediately and disinfecting pruning tools with bleach or alcohol. Resistant varieties carrying the Tm-2² gene offer the most reliable protection.",
    "Septoria leaf spot, caused by the fungus Septoria lycopersici, typically appears in warm, wet weather with frequent rain or overhead irrigation. Leaves develop small, circular spots with dark borders and gray centers speckled with tiny black fruiting bodies (pycnidia). As infection spreads upward, severe defoliation can occur, opening the canopy to sunscald on fruit. Management includes removing lower leaves to reduce humidity, applying fixed-copper or chlorothalonil sprays, and practicing crop rotation to non-host species.",
    "Target spot of tomato, often caused by Corynespora cassiicola, produces tan to brown leaf lesions with concentric ring patterns resembling a target. It thrives in warm, humid conditions and is spread by wind, rain splash, and contaminated stakes or tools. To control it, prune for better air flow, avoid working in fields when foliage is wet, and apply fungicides such as chlorothalonil when weather conditions favor disease. Removing and destroying severely infected foliage helps reduce the inoculum load for subsequent seasons.",
    "Two-spotted spider mite (Tetranychus urticae) isn’t a disease but a common pest whose feeding creates tiny pale stippling on leaves that can coalesce into large yellow patches. Severe infestations lead to fine webbing on the undersides of leaves and premature defoliation under hot, dry conditions. Introduce or conserve natural predators like predatory mites (Phytoseiulus persimilis), or apply miticides such as abamectin when thresholds are exceeded. Keeping plants well-watered and avoiding dust reduces outbreak severity.",
    "Tomato yellow leaf curl virus (TYLCV) is transmitted by the silverleaf whitefly (Bemisia tabaci) and causes downward leaf curling, yellowing between veins, and reduced plant vigor. Because no cure exists, preventive measures focus on using resistant cultivars, deploying reflective mulches to repel whiteflies, and applying systemic insecticides or biopesticides to suppress vector populations. Infected plants should be removed and destroyed immediately to prevent further spread within the crop."
]
